#define NOMINMAX
#include<windows.h>
#include<gl/gl.h>
#include<cmath>
#include<string>
#include<vector>
#include<algorithm>
#include<fstream>
using namespace std;
int MW=16,MH=16,CW=960,CH=540,RW=480,RH=270,renderScale=2,score=0,ammo=999;string world;vector<unsigned int>pix;vector<double>zbuf;double px=3,py=3,pa=0,hp=100;bool keyState[256],oldSpace=0,oldM=0,oldF2=0,showMap=1,mouseLook=1;HWND mainHwnd=0;HDC gDC=0;HGLRC gRC=0;GLuint tex=0;LARGE_INTEGER freq_,last_;
struct Enemy{double x,y;int hp;bool alive;};struct Item{double x,y;bool alive;};struct Hit{double dist;char c;double tex;bool edge;};vector<Enemy>enemies;vector<Item>items;
double PI(){return 3.14159265358979323846;}unsigned int rgb(int r,int g,int b){if(r<0)r=0;if(g<0)g=0;if(b<0)b=0;if(r>255)r=255;if(g>255)g=255;if(b>255)b=255;return 0xFF000000u|((unsigned)b<<16)|((unsigned)g<<8)|(unsigned)r;}double dis(double x1,double y1,double x2,double y2){double dx=x1-x2,dy=y1-y2;return sqrt(dx*dx+dy*dy);}double normAng(double a){double p=PI();while(a>p)a-=2*p;while(a<-p)a+=2*p;return a;}bool solidChar(char c){return c=='#'||c=='2'||c=='3'||c=='4';}char getMap(int x,int y){return x<0||y<0||x>=MW||y>=MH?'#':world[y*MW+x];}bool wall(double x,double y){return solidChar(getMap((int)x,(int)y));}
void writeDefaultMap(){ofstream out("map.txt");out<<"################\n#P....G........#\n#.......2222222#\n#..............#\n#......##......#\n#......##..E...#\n#..............#\n###............#\n##........G....#\n#......3333..###\n#......#.......#\n#..E...#.......#\n#..............#\n#......444444###\n#....G.......E.#\n################\n";}
void loadMap(){ifstream in("map.txt");if(!in.good())writeDefaultMap(),in.open("map.txt");vector<string>lines;string line;while(getline(in,line)){if(!line.empty()&&line[line.size()-1]=='\r')line.erase(line.size()-1);if(!line.empty())lines.push_back(line);}if(lines.empty()){writeDefaultMap();in.close();in.open("map.txt");while(getline(in,line)){if(!line.empty()&&line[line.size()-1]=='\r')line.erase(line.size()-1);if(!line.empty())lines.push_back(line);}}MH=lines.size();MW=0;for(int i=0;i<(int)lines.size();i++)if((int)lines[i].size()>MW)MW=lines[i].size();world.assign(MW*MH,'#');enemies.clear();items.clear();bool hasPlayer=0;for(int y=0;y<MH;y++)for(int x=0;x<MW;x++){char c=x<(int)lines[y].size()?lines[y][x]:'#';if(c=='P')px=x+.5,py=y+.5,pa=0,hasPlayer=1,c='.';else if(c=='E')enemies.push_back({x+.5,y+.5,3,1}),c='.';else if(c=='G')items.push_back({x+.5,y+.5,1}),c='.';world[y*MW+x]=c;}if(!hasPlayer)px=1.5,py=1.5,pa=0;}
void resetGame(){hp=100;score=0;ammo=999;loadMap();}
void putPixel(int x,int y,unsigned int c){if(x>=0&&x<RW&&y>=0&&y<RH)pix[y*RW+x]=c;}void rectPix(int x1,int y1,int x2,int y2,unsigned int c){if(x1<0)x1=0;if(y1<0)y1=0;if(x2>RW)x2=RW;if(y2>RH)y2=RH;for(int y=y1;y<y2;y++){unsigned int*row=&pix[y*RW];for(int x=x1;x<x2;x++)row[x]=c;}}void linePix(int x1,int y1,int x2,int y2,unsigned int c){int dx=abs(x2-x1),dy=-abs(y2-y1),sx=x1<x2?1:-1,sy=y1<y2?1:-1,err=dx+dy;for(;;){putPixel(x1,y1,c);if(x1==x2&&y1==y2)break;int e2=2*err;if(e2>=dy)err+=dy,x1+=sx;if(e2<=dx)err+=dx,y1+=sy;}}void circlePix(int cx,int cy,int r,unsigned int c){for(int y=-r;y<=r;y++)for(int x=-r;x<=r;x++)if(x*x+y*y<=r*r)putPixel(cx+x,cy+y,c);}
void resizeRenderBuffer(){RW=CW/renderScale;RH=CH/renderScale;if(RW<160)RW=160;if(RH<120)RH=120;pix.assign(RW*RH,0);zbuf.assign(RW,9999);if(tex)glDeleteTextures(1,&tex),tex=0;glGenTextures(1,&tex);glBindTexture(GL_TEXTURE_2D,tex);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA,RW,RH,0,GL_BGRA_EXT,GL_UNSIGNED_BYTE,&pix[0]);}
unsigned int texColor(char c,double dist,double texCoord,double vpos,bool sideShade){double light=1-dist/16;if(light<.1)light=.1;if(light>1)light=1;int r=210,g=210,b=230;if(c=='2')r=230,g=90,b=70;if(c=='3')r=70,g=150,b=235;if(c=='4')r=80,g=220,b=120;int tx=int(texCoord*8),ty=int(vpos*12),brickLine=0;if(ty%3==0)brickLine=1;if((tx+(ty/3)%2*4)%8==0)brickLine=1;double k=brickLine?.72:1;if(sideShade)k*=.78;return rgb(int(r*light*k),int(g*light*k),int(b*light*k));}
Hit castRay(double rayAngle){double rayX=sin(rayAngle),rayY=cos(rayAngle);int mapX=int(px),mapY=int(py);double deltaX=rayX==0?1e30:fabs(1/rayX),deltaY=rayY==0?1e30:fabs(1/rayY),sideX,sideY;int stepX,stepY;if(rayX<0)stepX=-1,sideX=(px-mapX)*deltaX;else stepX=1,sideX=(mapX+1.-px)*deltaX;if(rayY<0)stepY=-1,sideY=(py-mapY)*deltaY;else stepY=1,sideY=(mapY+1.-py)*deltaY;int side=0;char hitChar='#';for(int i=0;i<256;i++){if(sideX<sideY)sideX+=deltaX,mapX+=stepX,side=0;else sideY+=deltaY,mapY+=stepY,side=1;if(mapX<0||mapY<0||mapX>=MW||mapY>=MH){hitChar='#';break;}char c=getMap(mapX,mapY);if(solidChar(c)){hitChar=c;break;}}double dist;if(side==0)dist=(mapX-px+(1-stepX)/2.)/rayX;else dist=(mapY-py+(1-stepY)/2.)/rayY;if(dist<.001)dist=.001;if(dist>16)dist=16;double hitX=px+rayX*dist,hitY=py+rayY*dist,texCoord=side==0?hitY-floor(hitY):hitX-floor(hitX);return {dist,hitChar,texCoord,side==1};}
void shoot(){if(ammo<=0)return;ammo--;int best=-1;double bestDist=9999;for(int i=0;i<(int)enemies.size();i++){if(!enemies[i].alive)continue;double dx=enemies[i].x-px,dy=enemies[i].y-py,d=sqrt(dx*dx+dy*dy),angle=atan2(dx,dy),diff=fabs(normAng(angle-pa));if(diff<.08&&d<bestDist){bool blocked=0;double rayX=sin(angle),rayY=cos(angle);for(double t=0;t<d;t+=.08){double tx=px+rayX*t,ty=py+rayY*t;if(wall(tx,ty)){blocked=1;break;}}if(!blocked)best=i,bestDist=d;}}if(best!=-1){enemies[best].hp--;if(enemies[best].hp<=0)enemies[best].alive=0,score+=100;}}
void handleMouse(){if(!mouseLook||!mainHwnd)return;if(GetForegroundWindow()!=mainHwnd)return;RECT rc;GetClientRect(mainHwnd,&rc);POINT center{(rc.right-rc.left)/2,(rc.bottom-rc.top)/2},screenCenter=center;ClientToScreen(mainHwnd,&screenCenter);POINT p;GetCursorPos(&p);int dx=p.x-screenCenter.x;if(dx)pa+=dx*.0028,SetCursorPos(screenCenter.x,screenCenter.y);}
void updateGame(){LARGE_INTEGER now;QueryPerformanceCounter(&now);double dt=double(now.QuadPart-last_.QuadPart)/double(freq_.QuadPart);last_=now;if(dt>.05)dt=.05;handleMouse();if(keyState['R'])resetGame();if(keyState['M']&&!oldM)showMap=!showMap;oldM=keyState['M'];if(keyState[VK_F2]&&!oldF2){renderScale++;if(renderScale>4)renderScale=1;resizeRenderBuffer();}oldF2=keyState[VK_F2];if(keyState[VK_SPACE]&&!oldSpace)shoot();oldSpace=keyState[VK_SPACE];double sprint=keyState[VK_SHIFT]?1.7:1,moveSpeed=4.2*dt*sprint,nx=px,ny=py;if(keyState['W']||keyState[VK_UP])nx+=sin(pa)*moveSpeed,ny+=cos(pa)*moveSpeed;if(keyState['S']||keyState[VK_DOWN])nx-=sin(pa)*moveSpeed,ny-=cos(pa)*moveSpeed;if(keyState['A']||keyState[VK_LEFT])nx-=cos(pa)*moveSpeed,ny+=sin(pa)*moveSpeed;if(keyState['D']||keyState[VK_RIGHT])nx+=cos(pa)*moveSpeed,ny-=sin(pa)*moveSpeed;if(!wall(nx,py))px=nx;if(!wall(px,ny))py=ny;for(int i=0;i<(int)items.size();i++)if(items[i].alive&&dis(px,py,items[i].x,items[i].y)<.45)items[i].alive=0,score+=25;for(int i=0;i<(int)enemies.size();i++){if(!enemies[i].alive)continue;double d=dis(px,py,enemies[i].x,enemies[i].y);if(d<8&&d>.65){double vx=(px-enemies[i].x)/d,vy=(py-enemies[i].y)/d,ex=enemies[i].x+vx*dt*1.25,ey=enemies[i].y+vy*dt*1.25;if(!wall(ex,enemies[i].y))enemies[i].x=ex;if(!wall(enemies[i].x,ey))enemies[i].y=ey;}if(d<.85){hp-=35*dt;if(hp<0)hp=0;}}}
void drawSprite(double sx,double sy,unsigned int color,int type){const double FOV=3.14159265358979323846/3.;double dx=sx-px,dy=sy-py,dist=sqrt(dx*dx+dy*dy);if(dist<.1||dist>16)return;double angle=atan2(dx,dy),diff=normAng(angle-pa);if(fabs(diff)>FOV/2+.25)return;int screenX=int((.5+diff/FOV)*RW),size=int(RH/dist);if(type==1)size=int(size*.45);int top=RH/2-size/2,bottom=RH/2+size/2,left=screenX-size/2,right=screenX+size/2;if(right<0||left>=RW)return;int mid=(left+right)/2;if(mid>=0&&mid<RW&&dist>=zbuf[mid])return;if(type==1)circlePix(screenX,RH/2,size/2,color);else rectPix(left,top,right,bottom,color),rectPix(left+size/4,top-size/4,right-size/4,top+size/4,rgb(255,80,80));}
void drawMiniMap(){if(!showMap)return;int cell=RW<RH?RW/45:RH/45;if(cell<4)cell=4;int ox=8,oy=8;for(int y=0;y<MH;y++)for(int x=0;x<MW;x++){char c=getMap(x,y);unsigned int col;if(c=='#')col=rgb(220,220,220);else if(c=='2')col=rgb(220,120,90);else if(c=='3')col=rgb(80,150,220);else if(c=='4')col=rgb(100,220,120);else col=rgb(25,25,25);rectPix(ox+x*cell,oy+y*cell,ox+(x+1)*cell-1,oy+(y+1)*cell-1,col);}for(int i=0;i<(int)items.size();i++)if(items[i].alive)circlePix(ox+int(items[i].x*cell),oy+int(items[i].y*cell),2,rgb(255,220,40));for(int i=0;i<(int)enemies.size();i++)if(enemies[i].alive)circlePix(ox+int(enemies[i].x*cell),oy+int(enemies[i].y*cell),3,rgb(255,60,60));int sx=ox+int(px*cell),sy=oy+int(py*cell);circlePix(sx,sy,4,rgb(0,255,80));linePix(sx,sy,sx+int(sin(pa)*cell*1.8),sy+int(cos(pa)*cell*1.8),rgb(0,255,0));}
void drawCrosshair(){int cx=RW/2,cy=RH/2;unsigned int c=rgb(255,255,255);linePix(cx-10,cy,cx-4,cy,c);linePix(cx+4,cy,cx+10,cy,c);linePix(cx,cy-10,cx,cy-4,c);linePix(cx,cy+4,cx,cy+10,c);}
void drawHudPixels(){int x=12,y=RH-20,hpw=int(120*hp/100.);if(hpw<0)hpw=0;if(hpw>120)hpw=120;rectPix(x,y,x+124,y+12,rgb(40,0,0));rectPix(x+2,y+2,x+2+hpw,y+10,rgb(220,40,40));int sw=score%120;rectPix(x+140,y,x+264,y+12,rgb(0,35,0));rectPix(x+142,y+2,x+142+sw,y+10,rgb(40,220,80));int aw=ammo;if(aw>120)aw=120;rectPix(x+280,y,x+404,y+12,rgb(40,35,0));rectPix(x+282,y+2,x+282+aw,y+10,rgb(240,220,40));rectPix(RW-110,y,RW-10,y+12,rgb(20,20,20));if(mouseLook)rectPix(RW-108,y+2,RW-12,y+10,rgb(80,160,255));else rectPix(RW-108,y+2,RW-12,y+10,rgb(80,80,80));}
void renderPixels(){const double FOV=3.14159265358979323846/3.;for(int i=0;i<RW;i++)zbuf[i]=9999;for(int y=0;y<RH/2;y++){int v=40+y*100/max(1,RH/2);unsigned int c=rgb(v/2,v/2,v+80),*row=&pix[y*RW];for(int x=0;x<RW;x++)row[x]=c;}for(int y=RH/2;y<RH;y++){double b=1.-(double(y)-RH/2.)/(RH/2.);int v;if(b<.25)v=35;else if(b<.5)v=55;else if(b<.75)v=75;else if(b<.9)v=95;else v=120;unsigned int c=rgb(v,v,v),*row=&pix[y*RW];for(int x=0;x<RW;x++)row[x]=c;}for(int x=0;x<RW;x++){double rayAngle=pa-FOV/2.+double(x)/double(RW)*FOV;Hit h=castRay(rayAngle);double fixedDist=h.dist*cos(rayAngle-pa);if(fixedDist<.001)fixedDist=.001;zbuf[x]=fixedDist;int top=int(RH/2.-RH/fixedDist),bottom=RH-top;if(top<0)top=0;if(bottom>=RH)bottom=RH-1;int height=max(1,bottom-top);for(int y=top;y<=bottom;y++){double vpos=double(y-top)/double(height);pix[y*RW+x]=texColor(h.c,fixedDist,h.tex,vpos,h.edge);}}vector<pair<double,int> >order;for(int i=0;i<(int)items.size();i++)if(items[i].alive)order.push_back(make_pair(dis(px,py,items[i].x,items[i].y),1000+i));for(int i=0;i<(int)enemies.size();i++)if(enemies[i].alive)order.push_back(make_pair(dis(px,py,enemies[i].x,enemies[i].y),i));sort(order.rbegin(),order.rend());for(int i=0;i<(int)order.size();i++){int id=order[i].second;if(id>=1000){int k=id-1000;drawSprite(items[k].x,items[k].y,rgb(255,220,40),1);}else drawSprite(enemies[id].x,enemies[id].y,rgb(170,30,30),0);}drawMiniMap();drawCrosshair();drawHudPixels();if(hp<=0){rectPix(0,0,RW,RH,rgb(70,0,0));rectPix(RW/2-80,RH/2-10,RW/2+80,RH/2+10,rgb(180,20,20));}}
void presentOpenGL(){glViewport(0,0,CW,CH);glMatrixMode(GL_PROJECTION);glLoadIdentity();glOrtho(0,CW,CH,0,-1,1);glMatrixMode(GL_MODELVIEW);glLoadIdentity();glClear(GL_COLOR_BUFFER_BIT);glEnable(GL_TEXTURE_2D);glBindTexture(GL_TEXTURE_2D,tex);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,RW,RH,GL_BGRA_EXT,GL_UNSIGNED_BYTE,&pix[0]);glColor3ub(255,255,255);glBegin(GL_QUADS);glTexCoord2f(0,0);glVertex2f(0,0);glTexCoord2f(1,0);glVertex2f((float)CW,0);glTexCoord2f(1,1);glVertex2f((float)CW,(float)CH);glTexCoord2f(0,1);glVertex2f(0,(float)CH);glEnd();glDisable(GL_TEXTURE_2D);SwapBuffers(gDC);}
bool initOpenGL(HWND hwnd){gDC=GetDC(hwnd);PIXELFORMATDESCRIPTOR pfd;ZeroMemory(&pfd,sizeof(pfd));pfd.nSize=sizeof(pfd);pfd.nVersion=1;pfd.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER;pfd.iPixelType=PFD_TYPE_RGBA;pfd.cColorBits=32;pfd.cDepthBits=0;pfd.iLayerType=PFD_MAIN_PLANE;int pf=ChoosePixelFormat(gDC,&pfd);if(!pf)return 0;if(!SetPixelFormat(gDC,pf,&pfd))return 0;gRC=wglCreateContext(gDC);if(!gRC)return 0;if(!wglMakeCurrent(gDC,gRC))return 0;glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glDisable(GL_DITHER);glClearColor(0,0,0,1);resizeRenderBuffer();return 1;}
void destroyOpenGL(HWND hwnd){if(tex)glDeleteTextures(1,&tex),tex=0;if(gRC)wglMakeCurrent(NULL,NULL),wglDeleteContext(gRC),gRC=0;if(gDC)ReleaseDC(hwnd,gDC),gDC=0;}
LRESULT CALLBACK WindowProc(HWND hwnd,UINT msg,WPARAM wp,LPARAM lp){switch(msg){case WM_CREATE:mainHwnd=hwnd;initOpenGL(hwnd);ShowCursor(0);return 0;case WM_SIZE:CW=LOWORD(lp);CH=HIWORD(lp);if(CW<320)CW=320;if(CH<240)CH=240;if(gRC)resizeRenderBuffer();return 0;case WM_SETFOCUS:ShowCursor(0);return 0;case WM_KILLFOCUS:ShowCursor(1);return 0;case WM_KEYDOWN:if(wp<256)keyState[wp]=1;if(wp==VK_ESCAPE)DestroyWindow(hwnd);if(wp==VK_F1)mouseLook=!mouseLook,ShowCursor(!mouseLook);return 0;case WM_KEYUP:if(wp<256)keyState[wp]=0;return 0;case WM_LBUTTONDOWN:keyState[VK_SPACE]=1;return 0;case WM_LBUTTONUP:keyState[VK_SPACE]=0;return 0;case WM_DESTROY:ShowCursor(1);destroyOpenGL(hwnd);PostQuitMessage(0);return 0;}return DefWindowProc(hwnd,msg,wp,lp);}
int main(){HINSTANCE hInstance=GetModuleHandle(NULL);QueryPerformanceFrequency(&freq_);QueryPerformanceCounter(&last_);resetGame();WNDCLASS wc;ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=WindowProc;wc.hInstance=hInstance;wc.lpszClassName="TinyOpenGLRaycasterStable";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);RegisterClass(&wc);HWND hwnd=CreateWindow("TinyOpenGLRaycasterStable","Tiny C++ Raycaster - Stable OpenGL Texture Version",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,960,540,NULL,NULL,hInstance,NULL);mainHwnd=hwnd;ShowWindow(hwnd,SW_SHOW);UpdateWindow(hwnd);ShowCursor(0);MSG msg;for(;;){while(PeekMessage(&msg,NULL,0,0,PM_REMOVE)){if(msg.message==WM_QUIT)return 0;TranslateMessage(&msg);DispatchMessage(&msg);}if(hp>0)updateGame();else if(keyState['R'])resetGame();renderPixels();presentOpenGL();Sleep(1);}return 0;}